server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: recommendation-service
          uri: http://recommendation-service
          predicates:
            - Path=/recommendation-service/**
        - id: history-service
          uri: http://history-service
          predicates:
            - Path=/history-service/**
        - id: analytics-service
          uri: http://analytics-service
          predicates:
            - Path=/analytics-service/**
        - id: search-service
          uri: http://search-service
          predicates:
            - Path=/search-service/**
        - id: report-service
          uri: http://report-service
          predicates:
            - Path=/report-service/**

